---
- name: create user's Atom directory
  file:
    path: "/home/{{ item.user }}/.atom"
    state: directory
    mode: '0755'
    owner: "{{ item.user }}"
    group: "{{ item.group|default(item.user) }}"
  loop: "{{ atom_users }}"

- name: install Atom packages with apm
  command: "apm install {{ item.1 }}"
  become_user: "{{ item.0.user}}"
  loop: "{{ atom_users|subelements('packages', skip_missing=True) }}"
