---
- name: add atom debian APT repository GPG key
  apt_key:
    url: "{{ atom_apt_key_url }}"
    state: present

- name: add atom debian APT main repository
  apt_repository:
    repo: "deb [arch=amd64] {{ atom_apt_url }} any main"
    state: present
    filename: "atom_official"
  register: atom_apt_result

- name: apt update list for new atom repository
  apt:
    update_cache: yes
  when: atom_apt_result.changed

- name: install atom on debian
  apt:
    name: atom
    state: "{{ atom_version|default('present') }}"
